# Generated by Django 6.1.1 on 2026-09-23 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_registro', models.DateField()),
                ('conta', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LimiteDeGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conta', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_registro', models.DateField()),
                ('periodicidade', models.CharField(choices=[('mensal', 'Mensal'), ('anual', 'Anual')], max_length=10)),
                ('valor_limite', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conta', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_registro', models.DateField()),
                ('periodicidade', models.CharField(choices=[('mensal', 'Mensal'), ('anual', 'Anual')], max_length=10)),
                ('valor_meta', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Saida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_registro', models.DateField()),
                ('conta', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('num_parcelas', models.PositiveIntegerField(default=1)),
                ('valor_parcela', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_registro', models.DateField()),
                ('conta', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('numero', models.PositiveIntegerField()),
                ('data_vencimento', models.DateField()),
                ('saida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='nexo.saida')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
